---
title: "Lab 06 - Ugly charts and Simpson's paradox"
author: "Insert your name here"
date: "Insert date here"
output: github_document
---

### Load packages and data

```{r load-packages, message = FALSE}
library(tidyverse) 
library(dsbox)
library(mosaicData) 
```

### Exercise 1

# Data prep

```{r Ex1-data-rep}
staff <- read_csv("data/instructional-staff.csv")

staff_long <- staff %>%
  pivot_longer(cols = -faculty_type, names_to = "year") %>%
  mutate(value = as.numeric(value))

staff_long

staff_long %>%
  ggplot(aes(x = year, y = value, color = faculty_type)) +
  geom_line()
```

# An early attempt

```{r Ex1-early-attempt}
staff_long %>%
  ggplot(aes(
    x = year,
    y = value,
    group = faculty_type,
    color = faculty_type
  )) +
  geom_line()
```

# Fix the plot

```{r Ex1-fix}
staff_plot <- 
  ggplot(staff_long, aes(
    x = year,
    y = value,
    group = faculty_type,
    color = faculty_type
  )) +
  labs(title = "Instructional Staff Employment Trends", x = "Year", y = "Percentage", color = "Faculty Type") +
  theme(plot.title = element_text(hjust = 0.5)) +
  geom_line()

ggsave(staff_plot, file="staff_plot.pdf", width = 12, height = 4)

```

### Exercise 2

```{r Ex2}
part_time_staff <- staff[4, ] %>%
  pivot_longer(cols = -faculty_type, names_to = "year") %>%
  mutate(value = as.numeric(value))

part_time_staff_plot <- 
  ggplot(part_time_staff, aes(
    x = year,
    y = value,
    group = faculty_type,
    color = faculty_type
  )) +
  labs(title = "Instructional Staff Employment Trends", x = "Year", y = "Percentage", color = "Faculty Type") +
  theme(plot.title = element_text(hjust = 0.5)) +
  geom_line()

ggsave(part_time_staff_plot, file="part_time_staff_plot.pdf", width = 12, height = 4)
```

### Exercise 3

My idea is to onlt visualize the 10 most productive countries and lable the rest as others.
```{r Ex3}
fisheries <- read_csv("data/fisheries.csv")

fisheries <- fisheries %>% 
  arrange(desc(total))

other_capture <- sum(fisheries$capture[-(1:10)])
other_aquaculture <- sum(fisheries$aquaculture[-(1:10)])
other_total <- other_capture + other_aquaculture

fisheries_1 <- fisheries %>% 
  slice(1:10) %>% 
  #add_row(country = "Other", capture = other_capture, aquaculture = other_aquaculture, total = other_total) %>% 
  mutate(country = factor(country, levels = unique(country))) %>% 
  pivot_longer(cols = -country,
               names_to = "type",
               values_to = "value")
  

fisheries_line <- ggplot(fisheries_1, aes(x = country,
                      y = value,
                      color = type,
                      group = type)) +
  geom_line() +
  geom_point() +
  labs(title = "Countries with highest production", x = "Country", y = "Production", color = "Type") +
  theme(plot.title = element_text(hjust = 0.5))

ggsave(fisheries_line, file="fisheries_line.pdf", width = 12, height = 4)

fisheries_2 <- fisheries %>% 
  slice(1:10) %>% 
  add_row(country = "Other", capture = other_capture, aquaculture = other_aquaculture, total = other_total) %>% 
  mutate(country = factor(country, levels = unique(country))) 

ggplot(fisheries_2, aes(x = "", y = capture, fill = country)) +
  geom_col(width = 1) +
  coord_polar(theta = "y") +
  theme_void() +
  labs(title = "Capture by country", fill = "Country") +
  theme(plot.title = element_text(hjust = 0.5))

ggplot(fisheries_2, aes(x = "", y = aquaculture, fill = country)) +
  geom_col(width = 1) +
  coord_polar(theta = "y") +
  theme_void() +
  labs(title = "Aquaculture by country", fill = "Country") +
  theme(plot.title = element_text(hjust = 0.5))
```



